#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


no_index() {
  if curl -sSf ${ELASTIC_ENDPOINT}/persons >/dev/null; then
    echo "Index \"persons\" exists"
    return -1
  else
    return 0
  fi
}

create_index() {
  echo "No index found, creating..."
  curl -s -XPUT ${ELASTIC_ENDPOINT}/persons -H 'Content-Type: application/json' -d'
  {
    "settings": {
      "refresh_interval": "1s",
      "analysis": {
        "filter": {
          "english_stop": {
            "type":       "stop",
            "stopwords":  "_english_"
          },
          "english_stemmer": {
            "type": "stemmer",
            "language": "english"
          },
          "english_possessive_stemmer": {
            "type": "stemmer",
            "language": "possessive_english"
          },
          "russian_stop": {
            "type":       "stop",
            "stopwords":  "_russian_"
          },
          "russian_stemmer": {
            "type": "stemmer",
            "language": "russian"
          }
        },
        "analyzer": {
          "ru_en": {
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "english_stop",
              "english_stemmer",
              "english_possessive_stemmer",
              "russian_stop",
              "russian_stemmer"
            ]
          }
        }
      }
    },
    "mappings": {
      "dynamic": "strict",
      "properties": {
        "id": {
          "type": "keyword"
        },
        "name": {
          "type": "text",
          "analyzer": "ru_en"
        }
      }
    }
  }'
  echo "Index \"persons\" created successfully"
}

if no_index; then
  create_index
fi
