version: '3'
services:
  service:
    build: etl
    expose:
      - "8000"
  # из предыдущего
  nginx:
    container_name: nginxx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./configs:/etc/nginx/conf.d
      - ./data:/etc/data/
    depends_on:
      - service
    ports:
      - "80:80"

  db:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      etl/.env
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data

  # текущий
  elastic:
    container_name: elasticsearchh
    image: elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:
    driver: local